version: '3'

services:
  api:
    build: .
    container_name: tool-api-container
    ports:
      - "8011:8011"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./:/app
    restart: unless-stopped
    networks:
      - tool-network

networks:
  tool-network:
    name: tool-network